language: php
os: linux
cache:
    directories:
        - $HOME/.composer/cache/files

jobs:
    fast_finish: true
    include:
        -   php: 7.2
            env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

        -   php: 7.2
            env: DEPENDENCIES="symfony/symfony:^4.1"

        -   php: 7.2
            env: DEPENDENCIES="symfony/symfony:^5.0"

        -   php: 7.3
            env: DEPENDENCIES="symfony/symfony:^5.0"

        -   php: 7.4
            env: DEPENDENCIES="symfony/symfony:^5.0"

before_install:
    - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;

install:
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
    - composer validate --strict --no-check-lock
    - ./vendor/bin/simple-phpunit
