services:
    mailer_bundle.helper.mailer:
        class: Adamski\Symfony\MailerBundle\Helper\MailerHelper
        arguments:
            - "%mailer_bundle.mailer.sender_address%"
            - "%mailer_bundle.mailer.sender_name%"
            - "@swiftmailer.mailer.abstract"
            - "@twig"

    Adamski\Symfony\MailerBundle\Helper\MailerHelper:
        alias: mailer_bundle.helper.mailer
